### ISSUE TITLE
大佬,dev分支多久更新呀

### ISSUE THREAD

**Issue by phyYeung** [yaolunmao/vue-webtopo-svgeditor#1]

**Comment by yaolunmao** [comment]
您好 目前还没有更新的计划 等有时间再完善 而且目前可能公司要用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yaolunmao/vue-webtopo-svgeditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月5日(星期一) 下午2:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yaolunmao/vue-webtopo-svgeditor] 大佬,dev分支多久更新呀 (#1)

**Comment by phyYeung** [comment]
> 您目前还没有的计划等有时间再更新
> […](#)
> ------------------ 原始邮件 ------------------- 发件人: "yaolunmao/vue -webtopo-svgeditor" ***@***.***>; 发送时间： 2021年7月5日（星期一）下午2:15 ***@***.***>; ***@***.***>; 主题： [yaolunmao/vue-webtopo-svgeditor] 大佬，dev 近来更新呀 ( #1 ) — 你收到这个是因为你订阅了这个帖子。直接回复此邮件，在 GitHub 上查看，或取消订阅。

**Comment by phyYeung** [comment]
> 您好 目前还没有更新的计划 等有时间再完善 而且目前可能公司要用
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yaolunmao/vue-webtopo-svgeditor" ***@***.***&gt;; 发送时间:&nbsp;2021年7月5日(星期一) 下午2:15 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[yaolunmao/vue-webtopo-svgeditor] 大佬,dev分支多久更新呀 (#1) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
好的,多谢,向您学习一下,期待更新

**Comment by yaolunmao** [comment]
感谢支持，已发布
