### ISSUE TITLE
是否可以配置 修改svg中的动画参数？比如from 、to 、repeatCount

### ISSUE THREAD

**Issue by GitHubOfLeon** [yaolunmao/vue-webtopo-svgeditor#23]
有状态svg非常给力了，但是发现好像只能修改 fill  ，fill-opacity等等基本属性。
想问一下如何修改 比如reservoir中的animate中的属性呢？ 想动态控制水流的高度。

ps.我看之前2.1的版本好像支持在svg文件中动态绑定prop_data参数来控制属性的，这样可以分别控制svg的每一个‘小部分’的属性。现在的版本好像是直接给所有 ‘小部分’ 添加 ‘未配置过的属性’？
比如 circuit-breaker 中。path中设置了fill-opacity=1，在修改配置中的开关变量后，虽然给svg改变了fill-opacity的值，但是只有下面未配置fill-opacity的部分生效了。

说这么多其实就是  如果不能配置animate的属性来控制水流高度，我想着能不能在一个svg文件里，多放几个内置好的水流高度，然后通过第二种方式，控制某一个高度的水流显示，其他高度的水流隐藏，来达到目的。

**Comment by yaolunmao** [comment]
有状态组件实际上就是使用`symbol`定义图形模板，然后使用`use`进行实例化,但是`use`标签只能设置它的专有属性以及`svg`的全局属性，而且它会把属性透传到每个标签上。设计这个只是为了一些简单的场景可以不用写代码，具备复杂逻辑的场景我推荐使用自定义`svg`组件的方式，通过`props`传递需要用的属性，与2.1版本的思想是一样的，这样更加灵活,实现你所描述的需求也简单很多

**Comment by GitHubOfLeon** [comment]
收到！昨天回家路上也想到了，因为我看到大佬项目里的custom-svg了  template模板里一样可以通过props自定义。感谢大佬
