### ISSUE TITLE
自定义SVG的时候，选中时的缩放问题。

### ISSUE THREAD

**Issue by GitHubOfLeon** [yaolunmao/vue-webtopo-svgeditor#24]
我重新自定义了一个reservoir的svg，参照custom-svg-text的形式 写在了自定义的template里。
```
<template>
  <g>
    <rect
      transform="translate(360,360) rotate(180,0,0)"
      x="0"
      y="0"
      width="340"
      height="0"
      stroke="none"
    >
      <animate
        attributeName="height"
        from="0"
        :to="props.waterHeight"
        dur="5s"
        repeatCount="indefinite"
      />
    </rect>
    <polygon
      points="0,0 0,400 400,400 400,0 300,0 300,50 350,50 350,350 50,350 50,50 100,50 100,0"
      stroke-width="1"
    />
  </g>
</template>
<script setup lang="ts">
  const props = defineProps({
    waterHeight: {
      type: Number,
      default: 20
    }
  });
</script>
```
但是我发现在editor中，选中组件之后的缩放有抖动，怀疑是鼠标按下和move之后的动作中计算的scale问题，但是一时半会没看懂到底是啥问题。

自定义svg的时候  除了注册组件以外，还需要在什么地方 定义类似于scale或者坐标之类的相关参数吗？或者是宽高？
我录制了操作视频，希望作者指点一二     辛苦

https://user-images.githubusercontent.com/13461250/223343197-4df74f6d-7ffa-4624-9456-51293908c2c7.mov

**Comment by yaolunmao** [comment]
要保证自己画的`svg`必须是垂直和水平居中，然后这么引入
```
<!-- eslint-disable vue/html-indent -->
<template>
  <g :id="props.id">
    <symbol viewBox="0 0 1024 1024" :id="`${props.id}reservoir`">
      <rect transform="rotate(180,427,410)" x="0" y="0" width="680" height="400" stroke="none">
        <animate attributeName="height" from="0" to="400" dur="5s" repeatCount="indefinite" />
      </rect>
      <polygon
        points="283.2,131 87.7,129.1 85.1,911.2 938.9,911.2 938.9,131 740.8,131 740.8,241.3 849,245.4 853.1,807.1 
177.1,799.2 181.1,246.6 283.2,245 "
        stroke-width="10"
      />
    </symbol>
    <use :xlink:href="`#${props.id}reservoir`" width="100" height="100"></use>
  </g>
</template>
<script setup lang="ts">
  const props = defineProps({
    id: {
      type: String,
      default: ''
    }
  });
</script>


```

**Comment by GitHubOfLeon** [comment]
明白了，感谢大佬儿。
还有几个小问题叨扰一下哈 
1、
```
<use :xlink:href="`#${props.id}reservoir`" width="100" height="100"></use>
```
中的width和height我看结果，是影响拖动到面板上的组件初始大小的。但是如果我改成了200  200，还是会导致缩放问题和划线的锚点起始问题，想知道这块设置的原则是什么？固定100还是可以有其他方法配置？

2、关于props中的id，我起初以为是用来后续操作节点属性时候用于识别的，但是我看done_json里其实您给每一个拖动生成的组件默认给了一个tagName+随机字符串的操作，然后演示的操作里是直接操作了这个生成的节点id。
而且，我在自定义的svg组件 props中传入了一个id，最后在检查元素的时候发现元素的节点id 还是之前您生成的这个随机id，那我操作的时候 是需要遍历done_json中所有item，然后去匹配props中的id吗？

3、我看您部署在ruoyi上的示例项目，是支持了svg组件的绑定事件的，在webtopo-svg-preview中可以监听on-event-call-back的，想知道main分支是目前没有上线这个功能吗？还是这是需要付费的pro功能呀？

**Comment by yaolunmao** [comment]
1、我没有试过，理论上`viewBox="0 0 1024 1024"`的画布固定`100 100`即可，目前还没有发现问题。
2、这个id没什么用，就是为了防止多个组件定义模板冲突的，操作节点获取节点信息之类的要用导出里面的那个id，肯定不是在dom上获取
3、示例项目非开源版本，目前没有时间继续开发，后续开发完成有收费的打算，所以组件事件这里需要你自己在基础版上面加了

**Comment by GitHubOfLeon** [comment]
1和3都了解了。感谢回答 辛苦大佬。
关于2的问题，您说操作节点使用的id，是done_json中的那个id吗（就是tagname+随机字符串）？也就是说props中的id没用？还是我理解反了...

**Comment by yaolunmao** [comment]
props中的id是为了防止多个组件定义模板冲突的，有用是done_json中的那个id

**Comment by GitHubOfLeon** [comment]
了然。
辛苦大佬，打赏一杯咖啡  以示感谢  交个朋友。
/抱拳
