### ISSUE TITLE
如何动态修改svg中rect高度

### ISSUE THREAD

**Issue by LinYing89** [yaolunmao/vue-webtopo-svgeditor#29]
如何动态修改svg中rect高度, 如果有两个rect, 如何通过属性修改其中一个rect的height

**Comment by LinYing89** [comment]
[
![QQ截图20230505165019](https://user-images.githubusercontent.com/30618832/236415657-e866c18b-3c14-44b6-9ef9-11c6e43dcae6.png)
](url)页面上修改height值, 高度没有变化, 如何让里面的rect根据height值变化?

**Comment by yaolunmao** [comment]
高度是没有办法通过props设置的，如果是svg文件引入的的话props只能改symbol标签支持的，您这种需求需要使用自定义组件的方式，就可以使用props传值了

**Comment by LinYing89** [comment]
为什么自定义组件时, tag不是custom-svg-text就报错
![微信截图_20230505181448](https://user-images.githubusercontent.com/30618832/236432559-aebf45af-578d-4b1d-beed-77022d2cf9a6.png)
![微信截图_20230505181509](https://user-images.githubusercontent.com/30618832/236432607-d73bffc7-ab93-4b44-a3ad-85b4e65cf2cf.png)

**Comment by LinYing89** [comment]
程序里能不能加一个自定义组件, 可以修改rect高度的, 我试了好久没有做出来

**Comment by yaolunmao** [comment]
> 为什么自定义组件时, tag不是custom-svg-text就报错 ![微信截图_20230505181448](https://user-images.githubusercontent.com/30618832/236432559-aebf45af-578d-4b1d-beed-77022d2cf9a6.png) ![微信截图_20230505181509](https://user-images.githubusercontent.com/30618832/236432607-d73bffc7-ab93-4b44-a3ad-85b4e65cf2cf.png)

src\config-center\index.ts这个目录下 要把你写的组件按需导出一下

**Comment by yaolunmao** [comment]
> 程序里能不能加一个自定义组件, 可以修改rect高度的, 我试了好久没有做出来

和文字是一个道理，文字的字体还有大小怎么弄的，你的height也一样写就可以了
