### ISSUE TITLE
引入现有项目后报错

### ISSUE THREAD

**Issue by ninestep** [yaolunmao/vue-webtopo-svgeditor#37]
引入现有项目后报错
`Error: [🍍]: "getActivePinia()" was called but there was no active Pinia. Did you forget to install pinia?`
该怎么解决？`Pinia`已安装

**Comment by yaolunmao** [comment]
检查一下`pinia`是否注册成功了，注册`pinia`要在引用`WebtopoSvgEdit`插件之前才可以，或者可参考https://github.com/yaolunmao/vue-webtopo-svgeditor/tree/main/demo/vue-webtopo-svgeditor-example

**Comment by ninestep** [comment]
肯定是注册了，注册`pinia`是在`main.ts`,组件引用是在页面内，而且我是直接将你的示例复制进页面内
![image](https://github.com/yaolunmao/vue-webtopo-svgeditor/assets/13329058/e49e7588-2156-4535-a648-66b375223285)
![image](https://github.com/yaolunmao/vue-webtopo-svgeditor/assets/13329058/775972c9-1dfd-4681-95c5-bd69348ade71)

**Comment by ninestep** [comment]
另外我自己的程序也是使用`pinia`的，如果没有注册我的登录状态也不会生效

**Comment by yaolunmao** [comment]
```
import store from './store ' ;
```
不清楚你的store里面写了什么是否有冲突，如果没有冲突的话代码是没有问题的，能否提供一个可复现的最小示例项目？

**Comment by ninestep** [comment]
我尝试复现一下

**Comment by ninestep** [comment]
没有找到具体问题，但是把组件更新到最新后显示正常
