### ISSUE TITLE
大佬，请问能不能给组件设置节点，能够让鼠标点击两个组件之间的节点进行连线

### ISSUE THREAD

**Issue by isCopyman** [yaolunmao/vue-webtopo-svgeditor#5]
如果有相关的文章或者资料也请推荐一下，谢谢

**Comment by yaolunmao** [comment]
这个以后我会加 以直线为例 我目前的思路大概是每个组件都设置好锚点 然后选中连线功能再点击对应的锚点 将线的起终点坐标和锚点坐标绑定
连线的相关资料目前还没有 可视化的可以看下这个
[https://github.com/woai3c/Front-end-articles/issues/19](https://github.com/woai3c/Front-end-articles/issues/19)
